export const GET_ALL_BOOKS = 'GET_ALL_BOOKS';
export const SHOW_BOOK_DETAILS = 'SHOW_BOOK_DETAILS';
export const ADD_BOOK_TO_USER_CATALOG = 'ADD_BOOK_TO_USER_CATALOG';
export const REMOVE_BOOK_FROM_USER_CATALOG = 'REMOVE_BOOK_FROM_USER_CATALOG';
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

